// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2BjcyKpJSDDOqPogfaQaPkNEo9eRxHuU',
    appId: '1:117142809367:web:6dd487f89d638189a9a552',
    messagingSenderId: '117142809367',
    projectId: 'truckit-e2b48',
    authDomain: 'truckit-e2b48.firebaseapp.com',
    databaseURL: 'https://truckit-e2b48-default-rtdb.firebaseio.com',
    storageBucket: 'truckit-e2b48.appspot.com',
    measurementId: 'G-3QLYHXT4T4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAolP0DQpG-eIpizPV7GJlkRGQk1gm2hjI',
    appId: '1:117142809367:android:12747d8ccabd0b10a9a552',
    messagingSenderId: '117142809367',
    projectId: 'truckit-e2b48',
    databaseURL: 'https://truckit-e2b48-default-rtdb.firebaseio.com',
    storageBucket: 'truckit-e2b48.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALn0Vz4Q7_t2FVH5UNcZlQETckGeBfOJk',
    appId: '1:117142809367:ios:80f3c6bc5cc52ccba9a552',
    messagingSenderId: '117142809367',
    projectId: 'truckit-e2b48',
    databaseURL: 'https://truckit-e2b48-default-rtdb.firebaseio.com',
    storageBucket: 'truckit-e2b48.appspot.com',
    iosBundleId: 'com.example.truckitCustomerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALn0Vz4Q7_t2FVH5UNcZlQETckGeBfOJk',
    appId: '1:117142809367:ios:80f3c6bc5cc52ccba9a552',
    messagingSenderId: '117142809367',
    projectId: 'truckit-e2b48',
    databaseURL: 'https://truckit-e2b48-default-rtdb.firebaseio.com',
    storageBucket: 'truckit-e2b48.appspot.com',
    iosBundleId: 'com.example.truckitCustomerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2BjcyKpJSDDOqPogfaQaPkNEo9eRxHuU',
    appId: '1:117142809367:web:7f74b1c47e04346ea9a552',
    messagingSenderId: '117142809367',
    projectId: 'truckit-e2b48',
    authDomain: 'truckit-e2b48.firebaseapp.com',
    databaseURL: 'https://truckit-e2b48-default-rtdb.firebaseio.com',
    storageBucket: 'truckit-e2b48.appspot.com',
    measurementId: 'G-KMK1CQG07F',
  );
}